import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { BannerComponent } from '@/components/BannerComponent';
import { HypeLabContext, Environment, HypeLab, useNative } from 'hypelab-react';
import { NativeComponent } from '@/components/NativeComponent';

const client = new HypeLab({
  URL: 'https://api.hypelab-staging.com',
  propertySlug: 'dripdripdrip',
  environment: Environment.Development,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <main className={styles.main}>
        <HypeLabContext client={client}>
          <NativeComponent />
        </HypeLabContext>
      </main>
    </>
  );
}
